import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from 'components/Navbar'
import Profile from 'components/Profile'

import getYoutubeVideos from 'services/getYoutubeVideos'
import ListCardVideos from 'components/ListCardVideos'

export default function Home ({ videos }) {
  return (
    <>
      <Head>
        <title>Info MiduDev</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <Profile />
        <ListCardVideos videos={videos} />
      </main>
    </>
  )
}

export async function getStaticProps () {
  const videos = await getYoutubeVideos()

  return {
    props: {
      videos
    }
  }
}
